### PR TITLE
Adding fixes and tests

### PR DESCRIPTION
**Pull request by andrewpaliga**
- Fixed broken mollie gateways (remote tests now pass and the checkout works)
- Added unit tests for uncovered methods `get_request` and `post_request`

@girasquid @bizla can you review please?

### CODE REVIEW

**Comment by bizla** [comment]
Code looks good to me, although I'd amend the commit message to be more descriptive, like your PR description.

**Comment by girasquid** [comment]
Probably don't need ` test/unit/integrations/mollie/._mollie_test.rb`.

**Comment by girasquid** [comment]
Code looks ok though

**Comment by andrewpaliga** [comment]
grrr.. don't know how those keep sneaking in! thanks

**Pull request merged**
