### PR TITLE
Adding failed? accessor to notification class

### PR DESCRIPTION
**Pull request by andrewpaliga**
@girasquid @christianblais as discussed

### CODE REVIEW

**Comment by girasquid** [comment]
:+1:

**Comment by christianblais** [comment]
Hum, `status` should be standardized, right?

This one isn't;
https://github.com/Shopify/offsite_payments/blob/009a015458e8bdb7c5b5ade5789a2f580a477c0b/lib/offsite_payments/integrations/citrus.rb#L80-L93

This one returns `failure`, not `failed` as it should;
https://github.com/Shopify/offsite_payments/blob/009a015458e8bdb7c5b5ade5789a2f580a477c0b/lib/offsite_payments/integrations/liqpay.rb#L118-L120

Those are the first two I found, but we should go through them all.

**Comment by christianblais** [comment]
oops, closed?

**Comment by andrewpaliga** [comment]
Yeah .. see comment on other PR. Let me know if you think I should reopen

**Pull request closed without merging**
