### PR TITLE
Adding class methods to yuupay integration

### PR DESCRIPTION
**Pull request by andrewpaliga**
Fixes: The integration currently breaks Shopify because `Yuupay.return` doesn't exist. 

@girasquid @j-mutter review please

### CODE REVIEW

**Comment by girasquid** [comment]
:+1:

**Comment by camilo** [comment]
fix #38081  <-- so it auto-closes the issue

**Comment by j-mutter** [comment]
Should we just change the Universal module to define these, or is it not worth it if we're not going to be doing this for many gateways?

**Comment by andrewpaliga** [comment]
@j-mutter I don't see us doing this again for another gateway. It adds more work to integration universals.

**Comment by j-mutter** [comment]
Cool. :shipit:

**Pull request merged**
