### PR TITLE
Fixes thank you page on cancel

### PR DESCRIPTION
**Pull request by andrewpaliga**
Pass `cancel_return_url` to citrus

@girasquid @ivanfer

### CODE REVIEW

**Comment by girasquid** [comment]
Do we want to preserve the fact that this transaction is cancelled, not necessarily failed? Or is treating a cancel as a fail fine?

**Comment by andrewpaliga** [comment]
@girasquid ideally we'd be sending a cancel URL in the initial request and they'd be forwarding to that. We can reach out to Citrus at some point and see if this is a change they can make. In the meantime, this is a much better experience for customers. Currently they just get taken to a "thank you" page after they click cancel.

**Comment by andrewpaliga** [comment]
Alternatively, we can leave it as "Cancelled" and just add that as a string to the offsite processing job.

**Comment by girasquid** [comment]
This sounds like an improvement over what we have currently - :+1:. Having Citrus support cancel URLs down the road would be awesome.

**Comment by ivanfer** [comment]
:+1:

**Comment by andrewpaliga** [comment]
Citrus can't forward to cancel url .. reverted PR back to what it was before.

**Comment by andrewpaliga** [comment]
C'est bon?

**Comment by girasquid** [comment]
:+1:

**Pull request merged**
